version: 0.5.2.{build}
# 0.5.2.0 Don't dispose UDP client after each message send.
# 0.5.1.0 Bug fix. Null Reference Exception.
# 0.5.0.0 Change default facility value, add logingEvent.Properties to GelfMessage and a lot of small changes.
# 0.4.10.0 Added support for SSL over TCP in log4net
# 0.4.9.0 Send exception type along with the message and stacktrace
# 0.4.8.0 Support for custom fields in the config and through event properties
# 0.4.7.0 Added support for SSL over TCP
# 0.4.6.0 Added verbose flag            
# 0.4.5.0 Fix borken nuspecs                           
# 0.4.4.0 Bug fix. Unixtime + ms         
# 0.4.3.0 Limited EasyGelf.Log4net for Net 3.5         
# 0.4.2.0 Added logging.                                
# 0.4.1.0 Bugfixes. A lot of potential ArgumentNullException                                
# 0.4.0.0 Downgrade to .Net 4.0 and log4net 1.2.10                                
# 0.3.8.0 Inconsistent GelfMessage serialization, Increase default udp packet size                                
# 0.3.7.0 Remove JetBrains.Annotation and Newtonsoft.Json dependencies                                
# 0.3.6.0 IncludeStackTrace option                                
# 0.3.5.0 RemoteAddress could be dns name                                 
# 0.3.4.0 Now retries are supported                                 
# 0.3.3.0 AmqpTarget for NLog                                 
# 0.3.2.0 Delete UseBuffering option. Now it's true forever.
# 0.3.1.0 UdpTarget RemoteAddress initialization 
# 0.3.0.0 Basic NLog support 
# 0.2.3.0 Facility, LoggerName, ThreadName and Source Info
# 0.2.2.0 Transport Encoders
# 0.2.1.0 Buffered Transport
# 0.2.0.0 Merge all external dependencies except log4net into one assembly
# 0.1.0.0 Initial

platform: Any CPU
 
configuration: Release

assembly_info:
  patch: true
  file: Source\Version.cs
  assembly_version: "{version}"

before_build:
  nuget restore Source\EasyGelf.sln

build:
  parallel: true                
  project: Source\EasyGelf.sln
  verbosity: minimal
  publish_nuget: true  

                              
deploy:
  - provider: NuGet
    server:
    api_key:
      secure: iIiTNMuTc3em1in6hSSnWt7xaykACzfOZRSSLXLyN9rkWgh0mzYRvrDhSKuDIXcF
    on:
      branch: master
                                 
